from __future__ import annotations

from dataclasses import dataclass
from datetime import date


SEED_AS_OF_DATE = date(2026, 6, 9)
SCORE_VERSION = "mock-score-rules-2026-06-09"

SCORE_COMPONENTS = [
    ("financial_stability", 20),
    ("profitability", 15),
    ("growth", 15),
    ("valuation", 10),
    ("news_attention", 10),
    ("disclosure_event", 10),
    ("liquidity", 10),
    ("momentum_volatility", 10),
]


@dataclass(frozen=True)
class MockStock:
    ticker: str
    company_name: str
    company_name_en: str
    market: str
    sector: str
    industry: str
    listing_date: date
    corp_code: str
    base_score: int
    risk_tag: str
    risk_text: str


MOCK_STOCKS = [
    MockStock(
        ticker="005930",
        company_name="삼성전자",
        company_name_en="Samsung Electronics",
        market="KOSPI",
        sector="반도체",
        industry="전자부품 제조업",
        listing_date=date(1975, 6, 11),
        corp_code="MOCK00126380",
        base_score=78,
        risk_tag="sector_cycle",
        risk_text="업종 사이클 변화에 따라 단기 지표 해석이 달라질 수 있습니다.",
    ),
    MockStock(
        ticker="000660",
        company_name="SK하이닉스",
        company_name_en="SK hynix",
        market="KOSPI",
        sector="반도체",
        industry="메모리 반도체 제조업",
        listing_date=date(1996, 12, 26),
        corp_code="MOCK00164779",
        base_score=76,
        risk_tag="high_volatility",
        risk_text="최근 가격 변동성이 확대되어 추가 확인이 필요합니다.",
    ),
    MockStock(
        ticker="035420",
        company_name="NAVER",
        company_name_en="NAVER",
        market="KOSPI",
        sector="인터넷",
        industry="포털 및 플랫폼 서비스",
        listing_date=date(2002, 10, 29),
        corp_code="MOCK00266961",
        base_score=73,
        risk_tag="platform_regulation",
        risk_text="플랫폼 관련 정책 이슈가 지표 해석에 영향을 줄 수 있습니다.",
    ),
    MockStock(
        ticker="035720",
        company_name="카카오",
        company_name_en="Kakao",
        market="KOSPI",
        sector="인터넷",
        industry="모바일 플랫폼 서비스",
        listing_date=date(2017, 7, 10),
        corp_code="MOCK00258801",
        base_score=69,
        risk_tag="earnings_variability",
        risk_text="사업 부문별 실적 편차가 있어 세부 확인이 필요합니다.",
    ),
    MockStock(
        ticker="051910",
        company_name="LG화학",
        company_name_en="LG Chem",
        market="KOSPI",
        sector="화학",
        industry="기초 화학물질 제조업",
        listing_date=date(2001, 4, 25),
        corp_code="MOCK00356370",
        base_score=71,
        risk_tag="commodity_input_cost",
        risk_text="원재료 가격 변화가 수익성 지표에 영향을 줄 수 있습니다.",
    ),
    MockStock(
        ticker="006400",
        company_name="삼성SDI",
        company_name_en="Samsung SDI",
        market="KOSPI",
        sector="2차전지",
        industry="축전지 제조업",
        listing_date=date(1979, 2, 27),
        corp_code="MOCK00126362",
        base_score=72,
        risk_tag="demand_cycle",
        risk_text="전방 수요 변화에 따라 성장 지표 확인이 필요합니다.",
    ),
    MockStock(
        ticker="068270",
        company_name="셀트리온",
        company_name_en="Celltrion",
        market="KOSPI",
        sector="바이오",
        industry="바이오 의약품 제조업",
        listing_date=date(2018, 2, 9),
        corp_code="MOCK00413046",
        base_score=70,
        risk_tag="pipeline_timing",
        risk_text="제품 승인 및 공급 일정에 따른 변동 요인이 있습니다.",
    ),
    MockStock(
        ticker="005380",
        company_name="현대차",
        company_name_en="Hyundai Motor",
        market="KOSPI",
        sector="자동차",
        industry="자동차 제조업",
        listing_date=date(1974, 6, 28),
        corp_code="MOCK00164742",
        base_score=75,
        risk_tag="fx_sensitivity",
        risk_text="환율과 지역별 판매 흐름이 실적 지표에 영향을 줄 수 있습니다.",
    ),
    MockStock(
        ticker="000270",
        company_name="기아",
        company_name_en="Kia",
        market="KOSPI",
        sector="자동차",
        industry="자동차 제조업",
        listing_date=date(1973, 7, 21),
        corp_code="MOCK00164788",
        base_score=74,
        risk_tag="inventory_cycle",
        risk_text="재고와 판매 믹스 변화에 대한 확인이 필요합니다.",
    ),
    MockStock(
        ticker="012330",
        company_name="현대모비스",
        company_name_en="Hyundai Mobis",
        market="KOSPI",
        sector="자동차부품",
        industry="자동차 부품 제조업",
        listing_date=date(1989, 9, 5),
        corp_code="MOCK00164751",
        base_score=72,
        risk_tag="margin_pressure",
        risk_text="부품 원가와 납품 구조 변화가 마진 지표에 영향을 줄 수 있습니다.",
    ),
    MockStock(
        ticker="373220",
        company_name="LG에너지솔루션",
        company_name_en="LG Energy Solution",
        market="KOSPI",
        sector="2차전지",
        industry="축전지 제조업",
        listing_date=date(2022, 1, 27),
        corp_code="MOCK01640342",
        base_score=73,
        risk_tag="capacity_utilization",
        risk_text="공장 가동률과 고객사 수요 흐름 확인이 필요합니다.",
    ),
    MockStock(
        ticker="207940",
        company_name="삼성바이오로직스",
        company_name_en="Samsung Biologics",
        market="KOSPI",
        sector="바이오",
        industry="바이오 의약품 위탁생산",
        listing_date=date(2016, 11, 10),
        corp_code="MOCK00877059",
        base_score=77,
        risk_tag="contract_timing",
        risk_text="수주 인식 시점에 따라 분기별 지표가 달라질 수 있습니다.",
    ),
    MockStock(
        ticker="105560",
        company_name="KB금융",
        company_name_en="KB Financial Group",
        market="KOSPI",
        sector="금융",
        industry="금융지주회사",
        listing_date=date(2008, 10, 10),
        corp_code="MOCK00688996",
        base_score=74,
        risk_tag="interest_rate_cycle",
        risk_text="금리와 대손 비용 흐름에 대한 확인이 필요합니다.",
    ),
    MockStock(
        ticker="055550",
        company_name="신한지주",
        company_name_en="Shinhan Financial Group",
        market="KOSPI",
        sector="금융",
        industry="금융지주회사",
        listing_date=date(2001, 9, 10),
        corp_code="MOCK00382199",
        base_score=73,
        risk_tag="credit_cost",
        risk_text="신용 비용과 자본 비율 변화가 핵심 확인 지표입니다.",
    ),
    MockStock(
        ticker="086790",
        company_name="하나금융지주",
        company_name_en="Hana Financial Group",
        market="KOSPI",
        sector="금융",
        industry="금융지주회사",
        listing_date=date(2005, 12, 12),
        corp_code="MOCK00547583",
        base_score=72,
        risk_tag="margin_cycle",
        risk_text="순이자마진과 자산 건전성 흐름을 함께 봐야 합니다.",
    ),
    MockStock(
        ticker="034730",
        company_name="SK",
        company_name_en="SK Inc.",
        market="KOSPI",
        sector="지주",
        industry="지주회사",
        listing_date=date(2009, 11, 11),
        corp_code="MOCK00181712",
        base_score=70,
        risk_tag="portfolio_complexity",
        risk_text="주요 자회사별 실적 기여도 확인이 필요합니다.",
    ),
    MockStock(
        ticker="096770",
        company_name="SK이노베이션",
        company_name_en="SK Innovation",
        market="KOSPI",
        sector="에너지",
        industry="석유 정제품 제조업",
        listing_date=date(2007, 7, 25),
        corp_code="MOCK00631518",
        base_score=68,
        risk_tag="energy_spread",
        risk_text="정제마진과 에너지 가격 변화가 실적 지표에 영향을 줄 수 있습니다.",
    ),
    MockStock(
        ticker="003670",
        company_name="포스코퓨처엠",
        company_name_en="POSCO Future M",
        market="KOSPI",
        sector="2차전지",
        industry="이차전지 소재 제조업",
        listing_date=date(1989, 9, 5),
        corp_code="MOCK00155276",
        base_score=69,
        risk_tag="material_price",
        risk_text="소재 가격과 장기 공급계약 조건 확인이 필요합니다.",
    ),
    MockStock(
        ticker="005490",
        company_name="POSCO홀딩스",
        company_name_en="POSCO Holdings",
        market="KOSPI",
        sector="철강",
        industry="지주 및 철강",
        listing_date=date(1988, 6, 10),
        corp_code="MOCK00155319",
        base_score=71,
        risk_tag="steel_cycle",
        risk_text="철강 수요와 원재료 가격 흐름이 주요 확인 지표입니다.",
    ),
    MockStock(
        ticker="066570",
        company_name="LG전자",
        company_name_en="LG Electronics",
        market="KOSPI",
        sector="전자",
        industry="가전 및 전자제품 제조업",
        listing_date=date(2002, 4, 22),
        corp_code="MOCK00401731",
        base_score=70,
        risk_tag="consumer_demand",
        risk_text="소비 경기와 제품 믹스 변화에 따른 확인이 필요합니다.",
    ),
    MockStock(
        ticker="032830",
        company_name="삼성생명",
        company_name_en="Samsung Life Insurance",
        market="KOSPI",
        sector="보험",
        industry="생명보험업",
        listing_date=date(2010, 5, 12),
        corp_code="MOCK00126256",
        base_score=69,
        risk_tag="insurance_reserve",
        risk_text="보험 손익과 준비금 변화가 지표 해석에 영향을 줄 수 있습니다.",
    ),
    MockStock(
        ticker="000810",
        company_name="삼성화재",
        company_name_en="Samsung Fire & Marine Insurance",
        market="KOSPI",
        sector="보험",
        industry="손해보험업",
        listing_date=date(1975, 6, 30),
        corp_code="MOCK00126434",
        base_score=72,
        risk_tag="loss_ratio",
        risk_text="손해율과 운용 수익 변화를 함께 확인해야 합니다.",
    ),
    MockStock(
        ticker="090430",
        company_name="아모레퍼시픽",
        company_name_en="Amorepacific",
        market="KOSPI",
        sector="화장품",
        industry="화장품 제조업",
        listing_date=date(2006, 6, 29),
        corp_code="MOCK00583424",
        base_score=66,
        risk_tag="export_demand",
        risk_text="지역별 수요와 브랜드 비용 변화 확인이 필요합니다.",
    ),
    MockStock(
        ticker="018260",
        company_name="삼성에스디에스",
        company_name_en="Samsung SDS",
        market="KOSPI",
        sector="IT서비스",
        industry="시스템 통합 및 IT 서비스",
        listing_date=date(2014, 11, 14),
        corp_code="MOCK00126186",
        base_score=71,
        risk_tag="project_pipeline",
        risk_text="대형 프로젝트 진행률과 클라우드 전환 흐름 확인이 필요합니다.",
    ),
    MockStock(
        ticker="009150",
        company_name="삼성전기",
        company_name_en="Samsung Electro-Mechanics",
        market="KOSPI",
        sector="전자부품",
        industry="전자부품 제조업",
        listing_date=date(1979, 2, 27),
        corp_code="MOCK00126344",
        base_score=70,
        risk_tag="component_cycle",
        risk_text="부품 재고와 세트 수요 변화가 주요 확인 지표입니다.",
    ),
    MockStock(
        ticker="010950",
        company_name="S-Oil",
        company_name_en="S-Oil",
        market="KOSPI",
        sector="에너지",
        industry="석유 정제품 제조업",
        listing_date=date(1987, 5, 27),
        corp_code="MOCK00138262",
        base_score=67,
        risk_tag="refining_margin",
        risk_text="정제마진과 유가 변동에 대한 확인이 필요합니다.",
    ),
    MockStock(
        ticker="011200",
        company_name="HMM",
        company_name_en="HMM",
        market="KOSPI",
        sector="운송",
        industry="해상 운송업",
        listing_date=date(1995, 10, 5),
        corp_code="MOCK00164645",
        base_score=65,
        risk_tag="freight_rate_cycle",
        risk_text="운임 지표와 선복 공급 변화 확인이 필요합니다.",
    ),
    MockStock(
        ticker="028260",
        company_name="삼성물산",
        company_name_en="Samsung C&T",
        market="KOSPI",
        sector="상사/건설",
        industry="종합상사 및 건설",
        listing_date=date(2014, 12, 18),
        corp_code="MOCK00126371",
        base_score=72,
        risk_tag="project_execution",
        risk_text="건설 프로젝트 진행률과 원가 흐름 확인이 필요합니다.",
    ),
    MockStock(
        ticker="024110",
        company_name="기업은행",
        company_name_en="Industrial Bank of Korea",
        market="KOSPI",
        sector="금융",
        industry="은행업",
        listing_date=date(2003, 12, 24),
        corp_code="MOCK00149646",
        base_score=70,
        risk_tag="sme_credit",
        risk_text="중소기업 여신 건전성 흐름 확인이 필요합니다.",
    ),
    MockStock(
        ticker="316140",
        company_name="우리금융지주",
        company_name_en="Woori Financial Group",
        market="KOSPI",
        sector="금융",
        industry="금융지주회사",
        listing_date=date(2019, 2, 13),
        corp_code="MOCK01350869",
        base_score=71,
        risk_tag="capital_policy",
        risk_text="자본 정책과 비용 관리 흐름을 함께 확인해야 합니다.",
    ),
]
